import { readdirSync, readFileSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";

const distDir = join(import.meta.dir, "..", "ui", "dist");

const mimeTypes: Record<string, string> = {
  html: "text/html; charset=utf-8",
  css: "text/css; charset=utf-8",
  js: "application/javascript; charset=utf-8",
  json: "application/json",
  svg: "image/svg+xml",
  png: "image/png",
  ico: "image/x-icon",
  txt: "text/plain; charset=utf-8",
  xml: "application/xml",
  wasm: "application/wasm",
  gif: "image/gif",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  woff: "font/woff",
  woff2: "font/woff2",
  ttf: "font/ttf",
  otf: "font/otf",
  map: "application/json",
};

const textExts = new Set([
  "html", "htm", "css", "js", "mjs", "cjs", "json", "svg",
  "txt", "xml", "map", "wasm",
]);

const files: { path: string; content: string; mime: string }[] = [];

function walk(dir: string) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full);
    } else {
      const rel = "/" + relative(distDir, full);
      const ext = entry.split(".").pop()?.toLowerCase() ?? "";
      const buf = readFileSync(full);
      const isText = textExts.has(ext);
      const content = isText ? buf.toString("utf-8") : buf.toString("base64");
      const mime = mimeTypes[ext] ?? "application/octet-stream";
      files.push({ path: rel, content, mime });
    }
  }
}

walk(distDir);

const entries = files
  .map((f) => `  ${JSON.stringify(f.path)}: { c: ${JSON.stringify(f.content)}, m: ${JSON.stringify(f.mime)} }`)
  .join(",\n");

const code = `// Auto-generated by scripts/embed-ui.ts — do not edit

interface Asset {
  c: string;
  m: string;
}

const assets: Record<string, Asset> = {
${entries}
};

export function serveAsset(path: string): Response | null {
  const a = assets[path];
  if (!a) return null;
  const isBase64 = !/^[\\x20-\\x7E\\t\\n\\r]+$/.test(a.c.slice(0, 200));
  if (isBase64) {
    return new Response(Buffer.from(a.c, "base64"), {
      headers: { "Content-Type": a.m },
    });
  }
  return new Response(a.c, {
    headers: { "Content-Type": a.m },
  });
}

export function hasAsset(path: string): boolean {
  return path in assets;
}
`;

writeFileSync(join(import.meta.dir, "..", "src", "ui.assets.ts"), code);

console.log(`Embedded ${files.length} UI assets into src/ui.assets.ts`);
for (const f of files) {
  const size = f.mime.startsWith("text/") ? `${f.content.length} chars` : `${Buffer.byteLength(f.content, "base64")} bytes`;
  console.log(`  ${f.path} (${f.mime}, ${size})`);
}
